import ExpertiseGrid from "../components/ExpertiseGrid"
import SectionHeading from "../components/SectionHeading"
import Workflow from "../components/Workflow"
import { aiWorkflow, cv } from "../data/cv"
import { projects } from "../data/projects"

export default function CV() {
  const experience = cv.experience[0]
  return (
    <div className="mx-auto max-w-[1120px] px-5 py-10 sm:px-6 md:px-8 md:py-14 print:py-4">
      <header className="rounded-[22px] border hairline bg-white p-6 md:p-9"><div className="grid items-start gap-6 md:grid-cols-[100px_1fr]"><img src="/fotos/federico-profile.jpg" alt="Federico Lapido" className="h-[100px] w-[100px] rounded-[18px] border hairline object-cover object-[50%_28%]" /><div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-stone">Curriculum vitae · {cv.location}</div><h1 className="mt-3 font-display text-[42px] leading-[.94] tracking-[-.045em] md:text-[54px]">{cv.name}</h1><p className="mt-3 font-display text-[21px] leading-tight">{cv.title}</p><p className="mt-1 text-[13px] font-medium text-clay-dark">{cv.specialties}</p><p className="mt-4 max-w-[65ch] text-[14px] leading-relaxed text-ink-light">{cv.headline}</p><div className="mt-5 flex flex-wrap gap-2"><a href={cv.links.linkedin} target="_blank" rel="noopener noreferrer" className="rounded-full border hairline bg-paper-2 px-3.5 py-2 text-[12px]">LinkedIn ↗</a><a href={cv.links.github} target="_blank" rel="noopener noreferrer" className="rounded-full border hairline bg-paper-2 px-3.5 py-2 text-[12px]">GitHub ↗</a>{cv.hasPdf && <a href={cv.pdfPath} download className="rounded-full bg-ink px-3.5 py-2 text-[12px] text-paper">Descargar PDF ↓</a>}</div></div></div></header>

      <section className="mt-8"><SectionHeading eyebrow="Professional Summary" title="Backend, integraciones y calidad para software que necesita evolucionar." /><p className="mt-5 max-w-[80ch] text-[14px] leading-relaxed text-ink-light">{cv.summary}</p></section>

      <section id="experience" className="scroll-mt-20 mt-12"><SectionHeading eyebrow="Experience" title="WiseTech Global" /><article className="mt-6 overflow-hidden rounded-[20px] border hairline bg-white"><div className="grid md:grid-cols-[.32fr_.68fr]"><div className="bg-ink p-6 text-paper"><div className="font-mono text-[10px] uppercase tracking-[.14em] text-brass">{experience.period}</div><p className="mt-5 font-display text-[25px] leading-none">{experience.role}</p><p className="mt-3 text-[13px] text-paper/70">{experience.location}</p></div><div className="p-6"><p className="text-[14px] leading-relaxed text-ink-light">{experience.summary}</p><ul className="mt-5 grid gap-2 sm:grid-cols-2">{experience.chapters.map(item => <li key={item} className="border-t hairline pt-3 text-[13px] leading-relaxed">{item}</li>)}</ul></div></div></article></section>

      <section className="mt-12"><SectionHeading eyebrow="Career Highlights" title="Una trayectoria de ingeniería empresarial." /><div className="mt-6 flex flex-wrap gap-2">{cv.careerHighlights.map(item => <span key={item} className="rounded-full border hairline bg-paper-2 px-3 py-1.5 text-[11px]">{item}</span>)}</div></section>

      <section id="skills" className="scroll-mt-20 mt-12"><SectionHeading eyebrow="Engineering Expertise" title="Tecnologías y prácticas por área de trabajo." intro="El inventario incluye experiencia y conocimiento técnico; no representa porcentajes ni una promesa de especialización actual idéntica en cada elemento." /><div className="mt-7"><ExpertiseGrid /></div></section>

      <section className="mt-12 rounded-[22px] bg-ink p-6 text-paper md:p-9"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><SectionHeading eyebrow="AI Engineering" title="Acelerar con IA, revisar con criterio." light intro="IA aplicada al análisis de código, debugging, documentación, pruebas, refactoring y automatización; siempre con responsabilidad humana." /></div><Workflow steps={aiWorkflow} tone="dark" compact /></div></section>

      <section className="mt-12"><SectionHeading eyebrow="Selected Projects" title="Práctica y exploración." /><div className="mt-6 grid gap-3 md:grid-cols-3">{projects.filter(project => project.featured).map(project => <a href={project.href} key={project.slug} className="rounded-[16px] border hairline bg-white p-5 transition hover:bg-paper-2"><div className="font-mono text-[10px] uppercase tracking-[.13em]" style={{ color: project.color }}>{project.demoStatus}</div><h3 className="mt-4 font-display text-[20px] leading-none">{project.title}</h3><p className="mt-3 text-[12px] leading-relaxed text-ink-light">{project.description}</p></a>)}</div></section>

      <section className="mt-12 grid gap-4 md:grid-cols-3"><div className="rounded-[16px] border hairline bg-white p-5"><div className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Education</div><p className="mt-4 font-display text-[17px] leading-tight">{cv.education.title}</p><p className="mt-1 text-[12px] text-ink-light">{cv.education.place}</p></div><div className="rounded-[16px] border hairline bg-white p-5"><div className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Certification</div><p className="mt-4 font-display text-[17px] leading-tight">{cv.certification.title}</p><p className="mt-1 text-[12px] text-ink-light">{cv.certification.issuer} · {cv.certification.year}</p></div><div className="rounded-[16px] border hairline bg-white p-5"><div className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Languages</div><dl className="mt-4 space-y-3">{cv.languages.map(language => <div key={language.lang} className="flex gap-2 text-[12px]"><dt className="font-medium">{language.lang}</dt><dd className="text-ink-light">— {language.level}</dd></div>)}</dl></div></section>

      <section className="mt-8 rounded-[20px] border hairline bg-paper-2 p-6 md:flex md:items-center md:justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Contact</div><h2 className="mt-2 font-display text-[25px] leading-none">Federico Lapido</h2><p className="mt-2 text-[13px] text-ink-light">{cv.title} · {cv.location}</p></div><div className="mt-5 flex flex-wrap gap-2 md:mt-0"><a href={cv.links.linkedin} target="_blank" rel="noopener noreferrer" className="rounded-full bg-ink px-4 py-2.5 text-[12px] text-paper">LinkedIn ↗</a><a href={`mailto:${cv.links.email}`} className="rounded-full border hairline bg-white px-4 py-2.5 text-[12px]">Email</a></div></section>
      <p className="mt-5 text-center font-mono text-[10px] text-stone print:hidden">También podés imprimir esta página desde el navegador.</p>
    </div>
  )
}
