import { Link } from "react-router-dom"
import type { Project } from "../data/projects"

function LegacyEvidence() {
  return <section className="mt-12"><div className="mb-6"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-clay-dark">Antes → proceso → después</div><h2 className="mt-2 font-display text-[32px] leading-none">De una pantalla fija a una experiencia web preparada para evolucionar.</h2></div><div className="grid gap-4 lg:grid-cols-[1fr_auto_1fr] lg:items-center"><figure className="overflow-hidden rounded-[18px] border hairline bg-paper-2"><img src="/solutions/legacy/legacy-before.png" alt="Captura real de una pantalla de acceso de sistema desktop legado" className="w-full bg-[#D8D2C4] object-contain p-4" /><figcaption className="border-t hairline px-4 py-3 text-[12px]"><strong>Sistema viejo:</strong> interfaz desktop, resolución fija y formularios acoplados.</figcaption></figure><div className="hidden font-display text-[34px] text-clay-dark lg:block">→</div><figure className="overflow-hidden rounded-[18px] border hairline bg-white"><img src="/solutions/legacy/dashboard-demo.png" alt="Captura real del sistema web moderno con operaciones y panel de actividad" className="w-full object-cover object-top" /><figcaption className="border-t hairline px-4 py-3 text-[12px]"><strong>Sistema nuevo:</strong> operación más legible, módulos web y pantalla responsive.</figcaption></figure></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["1", "Analizar", "Entender reglas y procesos que ya funcionan."], ["2", "Preservar", "Separar comportamiento valioso antes de cambiar la interfaz."], ["3", "Migrar", "Incorporar APIs, web y pruebas en etapas controladas."]].map(([n,t,d]) => <div key={n} className="border-t hairline pt-3"><span className="font-mono text-[10px] text-clay-dark">0{n}</span><h3 className="mt-2 font-display text-[18px]">{t}</h3><p className="mt-1 text-[12px] leading-relaxed text-ink-light">{d}</p></div>)}</div></section>
}

function AuctionEvidence() {
  return <section className="mt-12 rounded-[22px] border hairline bg-paper-2/60 p-6 md:p-8"><div className="font-mono text-[10px] uppercase tracking-[.16em] text-clay-dark">Flujo de producto</div><h2 className="mt-2 font-display text-[32px] leading-none">Productos → detalle → oferta o compra → proceso.</h2><p className="mt-3 max-w-[65ch] text-[13px] leading-relaxed text-ink-light">La evidencia reúne catálogo, detalle, historial y reglas de la operación en una misma experiencia. Los datos que se muestran son ficticios.</p><div className="mt-6 grid gap-2 sm:grid-cols-5">{["Catálogo", "Detalle", "Oferta / compra", "Usuario", "Seguimiento"].map((step, index) => <div key={step} className="rounded-[12px] border hairline bg-white p-3"><span className="font-mono text-[10px] text-clay-dark">0{index + 1}</span><p className="mt-2 text-[12px] leading-tight">{step}</p></div>)}</div><div className="mt-6 border-t hairline pt-5"><h3 className="font-display text-[22px]">Esta base puede adaptarse a otros modelos</h3><p className="mt-2 text-[13px] text-ink-light">Catálogo de productos, venta directa, reservas, marketplace pequeño, licitaciones privadas, servicios o inventario comercial.</p></div></section>
}

function ArchiveEvidence() {
  return <section className="mt-12"><div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><figure className="overflow-hidden rounded-[18px] border hairline bg-paper-2"><img src="/solutions/archivo-digital/tucuman-public.png" alt="Captura real de Acervo Tucumán con ficha de material histórico público" className="w-full object-cover object-top" /><figcaption className="border-t hairline px-4 py-3 text-[12px] leading-relaxed">Evidencia real de Acervo Tucumán con información histórica pública y sin datos privados.</figcaption></figure><div><div className="font-mono text-[10px] uppercase tracking-[.16em] text-clay-dark">Lo que ya existe</div><h2 className="mt-2 font-display text-[32px] leading-none">Fichas, categorías, recursos y navegación para una colección.</h2><p className="mt-4 text-[13px] leading-relaxed text-ink-light">El producto implementa una experiencia estática con fichas de información, categorías, recursos asociados y soporte para documentos. Puede servir como base para archivos institucionales, investigación o documentación empresarial.</p><div className="mt-5 rounded-[14px] border hairline bg-paper-2/70 p-4"><div className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Posible evolución con IA</div><p className="mt-2 text-[12px] leading-relaxed text-ink-light">Búsqueda, clasificación, extracción y resumen de documentos son extensiones posibles; no se presentan como funcionalidades implementadas.</p></div></div></div></section>
}

export default function CommercialEvidence({ project }: { project: Project }) {
  const body = project.slug === "legacy-web" ? <LegacyEvidence /> : project.slug === "subastas" ? <AuctionEvidence /> : project.slug === "archivo-digital" ? <ArchiveEvidence /> : null
  if (!body) return null
  const title = project.slug === "subastas" ? "¿Querés algo parecido para otro tipo de venta o proceso?" : project.slug === "archivo-digital" ? "¿Necesitás organizar documentos, imágenes o información?" : "¿Tenés un sistema parecido?"
  return <>{body}<section className="mt-8 rounded-[18px] bg-ink p-6 text-paper md:flex md:items-center md:justify-between md:gap-8"><div><div className="font-mono text-[10px] uppercase tracking-[.15em] text-brass">{title}</div><p className="mt-2 text-[14px] leading-relaxed text-paper/75">Podemos empezar por entender el proceso actual y definir una primera mejora comprobable.</p></div><div className="mt-5 flex flex-wrap gap-2 md:mt-0"><Link to={`/contacto?origen=${project.slug}`} className="rounded-full bg-white px-5 py-3 text-[13px] font-medium text-ink">Contame tu idea →</Link><a href={`https://wa.me/5491157642626?text=${encodeURIComponent(`Hola Federico, vi tu portfolio y quería consultarte por ${project.title}.`)}`} target="_blank" rel="noopener noreferrer" className="rounded-full border border-white/20 px-5 py-3 text-[13px] text-paper">WhatsApp ↗</a></div></section></>
}
