import { useState } from "react";
import { trackEvent } from "../lib/analytics";

const portfolio = "https://federico-home.pages.dev/";
const reference = "https://federico-home.pages.dev/gracias?tipo=referencia";
const portfolioText = "Te comparto el portfolio de Federico Lapido: software, modernización, automatización e IA aplicada.";
const referenceText = "Trabajaste conmigo alguna vez? Si querés, podés dejar una referencia profesional en mi portfolio. Gracias!";

export default function ShareActions() {
  const [fallback, setFallback] = useState<"portfolio" | "reference" | null>(null), [notice, setNotice] = useState("");
  const share = async (type: "portfolio" | "reference") => { const url = type === "portfolio" ? portfolio : reference, text = type === "portfolio" ? portfolioText : referenceText, event = type === "portfolio" ? "portfolio_share" : "reference_invite_share"; trackEvent(event, "/gracias", "gracias"); if (navigator.share) { try { await navigator.share({ title: "Federico Lapido", text, url }); setNotice("Gracias por compartir."); return; } catch { /* offer fallback */ } } setFallback(type); };
  const copy = async (type: "portfolio" | "reference") => { try { await navigator.clipboard.writeText(type === "portfolio" ? portfolio : reference); setNotice("Enlace copiado."); trackEvent(type === "portfolio" ? "portfolio_share" : "reference_invite_copy", "/gracias", "gracias"); } catch { setNotice("No pude copiar el enlace."); } };
  const type = fallback || "portfolio", url = type === "portfolio" ? portfolio : reference, text = type === "portfolio" ? portfolioText : referenceText;
  return <section className="mt-6 border hairline bg-white p-5" aria-label="Compartir"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-stone">Compartir</p><p className="mt-1 text-sm text-ink-light">Si te resultó útil, podés acercárselo a alguien.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void share("portfolio")} className="rounded-full border hairline px-4 py-2 text-sm hover:border-ink">Compartir portfolio</button><button type="button" onClick={() => void share("reference")} className="rounded-full bg-ink px-4 py-2 text-sm text-paper">Invitar a dejar una referencia</button></div></div>{fallback && <div className="mt-4 flex flex-wrap gap-2 border-t hairline pt-4"><button type="button" onClick={() => void copy(type)} className="rounded-full border hairline px-3 py-2 text-xs">Copiar enlace</button><a href={`https://wa.me/5491157642626?text=${encodeURIComponent(`${text}\n\n${url}`)}`} target="_blank" rel="noreferrer" onClick={() => trackEvent(type === "portfolio" ? "portfolio_share" : "reference_invite_share", "/gracias", "gracias")} className="rounded-full border hairline px-3 py-2 text-xs">WhatsApp</a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer" onClick={() => trackEvent(type === "portfolio" ? "portfolio_share" : "reference_invite_share", "/gracias", "gracias")} className="rounded-full border hairline px-3 py-2 text-xs">LinkedIn</a></div>}<p className="mt-3 min-h-5 text-sm text-ink-light" aria-live="polite">{notice}</p></section>;
}
